### ISSUE TITLE
primer files for pychopper

### ISSUE THREAD

**Issue by CSdady** [Nextomics/SCAN-seq#1]
Hi Ding Tang,

Thank you for sharing your code for the SCAN-seq analysis.
In order to learn, I am going thru your analysis with the raw data from your 2020 Plos biology paper.
Could you share your primer filres ( fasta and cofig files) for Pychopper? 
Thank you.

**Comment by defendant602** [comment]
Here is an example of primer and config used:

```
$cat primer.fa
>MyVNP
TGAAACCTAAGAAGGCACCGTATCTTTT
>MySSP
AAGCAGTGGTATCAACGCAGAGTACATGGG

$cat primer_config.txt
+:MySSP,-MyVNP|-:MyVNP,-MySSP
```

SSP is always the same, but you may need to change the VNP sequence according to the cell barcode in your fastq file.
